// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: file_server.proto

package fileservice

import (
	"context"

	"file_server/api/v1/file_server"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetImageUrlsRequest            = file_server.BatchGetImageUrlsRequest
	BatchGetImageUrlsResponse           = file_server.BatchGetImageUrlsResponse
	BatchGetImageUrlsResponse_ImageInfo = file_server.BatchGetImageUrlsResponse_ImageInfo
	GetFileInfoRequest                  = file_server.GetFileInfoRequest
	GetFileInfoResponse                 = file_server.GetFileInfoResponse
	UploadAvatarOrIconRequest           = file_server.UploadAvatarOrIconRequest
	UploadAvatarOrIconResponse          = file_server.UploadAvatarOrIconResponse
	UploadFileRequest                   = file_server.UploadFileRequest
	UploadFileResponse                  = file_server.UploadFileResponse
	UploadImageRequest                  = file_server.UploadImageRequest
	UploadImageResponse                 = file_server.UploadImageResponse

	FileService interface {
		// 通用文件上传
		UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
		GetFileInfo(ctx context.Context, in *GetFileInfoRequest, opts ...grpc.CallOption) (*GetFileInfoResponse, error)
		// 图片专用接口(包含缩略图处理)
		UploadImage(ctx context.Context, in *UploadImageRequest, opts ...grpc.CallOption) (*UploadImageResponse, error)
		BatchGetImageUrls(ctx context.Context, in *BatchGetImageUrlsRequest, opts ...grpc.CallOption) (*BatchGetImageUrlsResponse, error)
		// 头像图标上传(兼容旧接口)
		UploadUserAvatar(ctx context.Context, in *UploadAvatarOrIconRequest, opts ...grpc.CallOption) (*UploadAvatarOrIconResponse, error)
		UploadActivityIcon(ctx context.Context, in *UploadAvatarOrIconRequest, opts ...grpc.CallOption) (*UploadAvatarOrIconResponse, error)
	}

	defaultFileService struct {
		cli zrpc.Client
	}
)

func NewFileService(cli zrpc.Client) FileService {
	return &defaultFileService{
		cli: cli,
	}
}

// 通用文件上传
func (m *defaultFileService) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	client := file_server.NewFileServiceClient(m.cli.Conn())
	return client.UploadFile(ctx, in, opts...)
}

func (m *defaultFileService) GetFileInfo(ctx context.Context, in *GetFileInfoRequest, opts ...grpc.CallOption) (*GetFileInfoResponse, error) {
	client := file_server.NewFileServiceClient(m.cli.Conn())
	return client.GetFileInfo(ctx, in, opts...)
}

// 图片专用接口(包含缩略图处理)
func (m *defaultFileService) UploadImage(ctx context.Context, in *UploadImageRequest, opts ...grpc.CallOption) (*UploadImageResponse, error) {
	client := file_server.NewFileServiceClient(m.cli.Conn())
	return client.UploadImage(ctx, in, opts...)
}

func (m *defaultFileService) BatchGetImageUrls(ctx context.Context, in *BatchGetImageUrlsRequest, opts ...grpc.CallOption) (*BatchGetImageUrlsResponse, error) {
	client := file_server.NewFileServiceClient(m.cli.Conn())
	return client.BatchGetImageUrls(ctx, in, opts...)
}

// 头像图标上传(兼容旧接口)
func (m *defaultFileService) UploadUserAvatar(ctx context.Context, in *UploadAvatarOrIconRequest, opts ...grpc.CallOption) (*UploadAvatarOrIconResponse, error) {
	client := file_server.NewFileServiceClient(m.cli.Conn())
	return client.UploadUserAvatar(ctx, in, opts...)
}

func (m *defaultFileService) UploadActivityIcon(ctx context.Context, in *UploadAvatarOrIconRequest, opts ...grpc.CallOption) (*UploadAvatarOrIconResponse, error) {
	client := file_server.NewFileServiceClient(m.cli.Conn())
	return client.UploadActivityIcon(ctx, in, opts...)
}
