syntax = "proto3";

package file_server;
option go_package="./file_server";

// 定义文件存储服务
service FileService {
  // 上传用户头像
  rpc UploadUserAvatar(UploadAvatarOrIconRequest) returns (UploadAvatarOrIconResponse) {}
  rpc GetUserAvatarUrl(GetAvatarOrIconUrlRequest) returns (GetAvatarOrIconUrlResponse) {}
  // 上传活动图标
  rpc UploadActivityIcon(UploadAvatarOrIconRequest) returns (UploadAvatarOrIconResponse) {}
  rpc GetActivityIconUrl(GetAvatarOrIconUrlRequest) returns (GetAvatarOrIconUrlResponse) {}
  // 上传图片(消息)
  rpc UploadImage(UploadImageRequest) returns (UploadImageResponse) {}
  rpc GetImageUrl(GetImageUrlRequest) returns (GetImageUrlResponse) {}
  // 上传文件(消息)
  rpc UploadFile(UploadFileRequest) returns (UploadFileResponse) {}
  rpc GetFileUrl(GetFileUrlRequest) returns (GetFileUrlResponse) {}
}

// 头像图标上传请求消息结构体
message UploadAvatarOrIconRequest {
  int64 id = 1;
  bytes file_content = 2;
  string file_name = 3;
  string file_type = 4;
}

// 头像图标上传响应消息结构体
message UploadAvatarOrIconResponse {
  string file_url = 1;
}

message GetAvatarOrIconUrlRequest {
  int64 id = 1;
}

message GetAvatarOrIconUrlResponse {
  string file_url = 1;
}

// 图片上传请求消息结构体
message UploadImageRequest {
  bytes file_content = 2;
  string file_name = 3;
  string file_type = 4;
}
message UploadImageResponse {
  int64 id = 1;
  string file_url = 2;
}
message GetImageUrlRequest {
  int64 id = 1;
}
message GetImageUrlResponse {
  string file_url = 1;
}

// 文件上传请求消息结构体
message UploadFileRequest {
  bytes file_content = 2;
  string file_name = 3;
  string file_type = 4;
}
message UploadFileResponse {
  int64 id = 1;
  string file_url = 2;
}
message GetFileUrlRequest {
  int64 id = 1;
}
message GetFileUrlResponse {
  string file_url = 1;
}
// 服务端
// goctl rpc protoc file_server.proto --go_out=./api/v1 --go-grpc_out=./api/v1 --zrpc_out=. --style=go_zero
// 客户端
// goctl rpc protoc file_server.proto --go_out=./api/v1 --go-grpc_out=./api/v1 --zrpc_out=. --client=true --style=go_zero