// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: file_server.proto

package server

import (
	"context"

	"file_server/api/v1/file_server"
	"file_server/internal/logic"
	"file_server/internal/svc"
)

type FileServiceServer struct {
	svcCtx *svc.ServiceContext
	file_server.UnimplementedFileServiceServer
}

func NewFileServiceServer(svcCtx *svc.ServiceContext) *FileServiceServer {
	return &FileServiceServer{
		svcCtx: svcCtx,
	}
}

// 通用文件上传
func (s *FileServiceServer) UploadFile(ctx context.Context, in *file_server.UploadFileRequest) (*file_server.UploadFileResponse, error) {
	l := logic.NewUploadFileLogic(ctx, s.svcCtx)
	return l.UploadFile(in)
}

func (s *FileServiceServer) GetFileInfo(ctx context.Context, in *file_server.GetFileInfoRequest) (*file_server.GetFileInfoResponse, error) {
	l := logic.NewGetFileInfoLogic(ctx, s.svcCtx)
	return l.GetFileInfo(in)
}

// 图片专用接口(包含缩略图处理)
func (s *FileServiceServer) UploadImage(ctx context.Context, in *file_server.UploadImageRequest) (*file_server.UploadImageResponse, error) {
	l := logic.NewUploadImageLogic(ctx, s.svcCtx)
	return l.UploadImage(in)
}

func (s *FileServiceServer) BatchGetImageUrls(ctx context.Context, in *file_server.BatchGetImageUrlsRequest) (*file_server.BatchGetImageUrlsResponse, error) {
	l := logic.NewBatchGetImageUrlsLogic(ctx, s.svcCtx)
	return l.BatchGetImageUrls(in)
}

// 头像图标上传(兼容旧接口)
func (s *FileServiceServer) UploadUserAvatar(ctx context.Context, in *file_server.UploadAvatarOrIconRequest) (*file_server.UploadAvatarOrIconResponse, error) {
	l := logic.NewUploadUserAvatarLogic(ctx, s.svcCtx)
	return l.UploadUserAvatar(in)
}

func (s *FileServiceServer) UploadActivityIcon(ctx context.Context, in *file_server.UploadAvatarOrIconRequest) (*file_server.UploadAvatarOrIconResponse, error) {
	l := logic.NewUploadActivityIconLogic(ctx, s.svcCtx)
	return l.UploadActivityIcon(in)
}
