// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: file_server.proto

package server

import (
	"context"

	"file_server/api/v1/file_server"
	"file_server/internal/logic"
	"file_server/internal/svc"
)

type FileServiceServer struct {
	svcCtx *svc.ServiceContext
	file_server.UnimplementedFileServiceServer
}

func NewFileServiceServer(svcCtx *svc.ServiceContext) *FileServiceServer {
	return &FileServiceServer{
		svcCtx: svcCtx,
	}
}

// 上传用户头像
func (s *FileServiceServer) UploadUserAvatar(ctx context.Context, in *file_server.UploadAvatarOrIconRequest) (*file_server.UploadAvatarOrIconResponse, error) {
	l := logic.NewUploadUserAvatarLogic(ctx, s.svcCtx)
	return l.UploadUserAvatar(in)
}

func (s *FileServiceServer) GetUserAvatarUrl(ctx context.Context, in *file_server.GetAvatarOrIconUrlRequest) (*file_server.GetAvatarOrIconUrlResponse, error) {
	l := logic.NewGetUserAvatarUrlLogic(ctx, s.svcCtx)
	return l.GetUserAvatarUrl(in)
}

// 上传活动图标
func (s *FileServiceServer) UploadActivityIcon(ctx context.Context, in *file_server.UploadAvatarOrIconRequest) (*file_server.UploadAvatarOrIconResponse, error) {
	l := logic.NewUploadActivityIconLogic(ctx, s.svcCtx)
	return l.UploadActivityIcon(in)
}

func (s *FileServiceServer) GetActivityIconUrl(ctx context.Context, in *file_server.GetAvatarOrIconUrlRequest) (*file_server.GetAvatarOrIconUrlResponse, error) {
	l := logic.NewGetActivityIconUrlLogic(ctx, s.svcCtx)
	return l.GetActivityIconUrl(in)
}

// 上传图片(消息)
func (s *FileServiceServer) UploadImage(ctx context.Context, in *file_server.UploadImageRequest) (*file_server.UploadImageResponse, error) {
	l := logic.NewUploadImageLogic(ctx, s.svcCtx)
	return l.UploadImage(in)
}

func (s *FileServiceServer) GetImageUrl(ctx context.Context, in *file_server.GetImageUrlRequest) (*file_server.GetImageUrlResponse, error) {
	l := logic.NewGetImageUrlLogic(ctx, s.svcCtx)
	return l.GetImageUrl(in)
}

// 上传文件(消息)
func (s *FileServiceServer) UploadFile(ctx context.Context, in *file_server.UploadFileRequest) (*file_server.UploadFileResponse, error) {
	l := logic.NewUploadFileLogic(ctx, s.svcCtx)
	return l.UploadFile(in)
}

func (s *FileServiceServer) GetFileUrl(ctx context.Context, in *file_server.GetFileUrlRequest) (*file_server.GetFileUrlResponse, error) {
	l := logic.NewGetFileUrlLogic(ctx, s.svcCtx)
	return l.GetFileUrl(in)
}
