// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: file_server.proto

package server

import (
	"context"

	"file_server/api/v1/file_server"
	"file_server/internal/logic"
	"file_server/internal/svc"
)

type FileServiceServer struct {
	svcCtx *svc.ServiceContext
	file_server.UnimplementedFileServiceServer
}

func NewFileServiceServer(svcCtx *svc.ServiceContext) *FileServiceServer {
	return &FileServiceServer{
		svcCtx: svcCtx,
	}
}

// 上传文件的RPC方法
func (s *FileServiceServer) UploadAvatar(ctx context.Context, in *file_server.UploadAvatarRequest) (*file_server.UploadAvatarResponse, error) {
	l := logic.NewUploadAvatarLogic(ctx, s.svcCtx)
	return l.UploadAvatar(in)
}

func (s *FileServiceServer) GetAvatarUrl(ctx context.Context, in *file_server.GetAvatarUrlRequest) (*file_server.GetAvatarUrlResponse, error) {
	l := logic.NewGetAvatarUrlLogic(ctx, s.svcCtx)
	return l.GetAvatarUrl(in)
}
