// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: file_server.proto

package file_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileService_UploadUserAvatar_FullMethodName   = "/file_server.FileService/UploadUserAvatar"
	FileService_GetUserAvatarUrl_FullMethodName   = "/file_server.FileService/GetUserAvatarUrl"
	FileService_UploadActivityIcon_FullMethodName = "/file_server.FileService/UploadActivityIcon"
	FileService_GetActivityIconUrl_FullMethodName = "/file_server.FileService/GetActivityIconUrl"
	FileService_UploadImage_FullMethodName        = "/file_server.FileService/UploadImage"
	FileService_GetImageUrl_FullMethodName        = "/file_server.FileService/GetImageUrl"
	FileService_UploadFile_FullMethodName         = "/file_server.FileService/UploadFile"
	FileService_GetFileUrl_FullMethodName         = "/file_server.FileService/GetFileUrl"
)

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义文件存储服务
type FileServiceClient interface {
	// 上传用户头像
	UploadUserAvatar(ctx context.Context, in *UploadAvatarOrIconRequest, opts ...grpc.CallOption) (*UploadAvatarOrIconResponse, error)
	GetUserAvatarUrl(ctx context.Context, in *GetAvatarOrIconUrlRequest, opts ...grpc.CallOption) (*GetAvatarOrIconUrlResponse, error)
	// 上传活动图标
	UploadActivityIcon(ctx context.Context, in *UploadAvatarOrIconRequest, opts ...grpc.CallOption) (*UploadAvatarOrIconResponse, error)
	GetActivityIconUrl(ctx context.Context, in *GetAvatarOrIconUrlRequest, opts ...grpc.CallOption) (*GetAvatarOrIconUrlResponse, error)
	// 上传图片(消息)
	UploadImage(ctx context.Context, in *UploadImageRequest, opts ...grpc.CallOption) (*UploadImageResponse, error)
	GetImageUrl(ctx context.Context, in *GetImageUrlRequest, opts ...grpc.CallOption) (*GetImageUrlResponse, error)
	// 上传文件(消息)
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
	GetFileUrl(ctx context.Context, in *GetFileUrlRequest, opts ...grpc.CallOption) (*GetFileUrlResponse, error)
}

type fileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServiceClient(cc grpc.ClientConnInterface) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) UploadUserAvatar(ctx context.Context, in *UploadAvatarOrIconRequest, opts ...grpc.CallOption) (*UploadAvatarOrIconResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadAvatarOrIconResponse)
	err := c.cc.Invoke(ctx, FileService_UploadUserAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetUserAvatarUrl(ctx context.Context, in *GetAvatarOrIconUrlRequest, opts ...grpc.CallOption) (*GetAvatarOrIconUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvatarOrIconUrlResponse)
	err := c.cc.Invoke(ctx, FileService_GetUserAvatarUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) UploadActivityIcon(ctx context.Context, in *UploadAvatarOrIconRequest, opts ...grpc.CallOption) (*UploadAvatarOrIconResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadAvatarOrIconResponse)
	err := c.cc.Invoke(ctx, FileService_UploadActivityIcon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetActivityIconUrl(ctx context.Context, in *GetAvatarOrIconUrlRequest, opts ...grpc.CallOption) (*GetAvatarOrIconUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvatarOrIconUrlResponse)
	err := c.cc.Invoke(ctx, FileService_GetActivityIconUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) UploadImage(ctx context.Context, in *UploadImageRequest, opts ...grpc.CallOption) (*UploadImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadImageResponse)
	err := c.cc.Invoke(ctx, FileService_UploadImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetImageUrl(ctx context.Context, in *GetImageUrlRequest, opts ...grpc.CallOption) (*GetImageUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetImageUrlResponse)
	err := c.cc.Invoke(ctx, FileService_GetImageUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileResponse)
	err := c.cc.Invoke(ctx, FileService_UploadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetFileUrl(ctx context.Context, in *GetFileUrlRequest, opts ...grpc.CallOption) (*GetFileUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileUrlResponse)
	err := c.cc.Invoke(ctx, FileService_GetFileUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
// All implementations must embed UnimplementedFileServiceServer
// for forward compatibility.
//
// 定义文件存储服务
type FileServiceServer interface {
	// 上传用户头像
	UploadUserAvatar(context.Context, *UploadAvatarOrIconRequest) (*UploadAvatarOrIconResponse, error)
	GetUserAvatarUrl(context.Context, *GetAvatarOrIconUrlRequest) (*GetAvatarOrIconUrlResponse, error)
	// 上传活动图标
	UploadActivityIcon(context.Context, *UploadAvatarOrIconRequest) (*UploadAvatarOrIconResponse, error)
	GetActivityIconUrl(context.Context, *GetAvatarOrIconUrlRequest) (*GetAvatarOrIconUrlResponse, error)
	// 上传图片(消息)
	UploadImage(context.Context, *UploadImageRequest) (*UploadImageResponse, error)
	GetImageUrl(context.Context, *GetImageUrlRequest) (*GetImageUrlResponse, error)
	// 上传文件(消息)
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error)
	GetFileUrl(context.Context, *GetFileUrlRequest) (*GetFileUrlResponse, error)
	mustEmbedUnimplementedFileServiceServer()
}

// UnimplementedFileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServiceServer struct{}

func (UnimplementedFileServiceServer) UploadUserAvatar(context.Context, *UploadAvatarOrIconRequest) (*UploadAvatarOrIconResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadUserAvatar not implemented")
}
func (UnimplementedFileServiceServer) GetUserAvatarUrl(context.Context, *GetAvatarOrIconUrlRequest) (*GetAvatarOrIconUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAvatarUrl not implemented")
}
func (UnimplementedFileServiceServer) UploadActivityIcon(context.Context, *UploadAvatarOrIconRequest) (*UploadAvatarOrIconResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadActivityIcon not implemented")
}
func (UnimplementedFileServiceServer) GetActivityIconUrl(context.Context, *GetAvatarOrIconUrlRequest) (*GetAvatarOrIconUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivityIconUrl not implemented")
}
func (UnimplementedFileServiceServer) UploadImage(context.Context, *UploadImageRequest) (*UploadImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadImage not implemented")
}
func (UnimplementedFileServiceServer) GetImageUrl(context.Context, *GetImageUrlRequest) (*GetImageUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImageUrl not implemented")
}
func (UnimplementedFileServiceServer) UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedFileServiceServer) GetFileUrl(context.Context, *GetFileUrlRequest) (*GetFileUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileUrl not implemented")
}
func (UnimplementedFileServiceServer) mustEmbedUnimplementedFileServiceServer() {}
func (UnimplementedFileServiceServer) testEmbeddedByValue()                     {}

// UnsafeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServiceServer will
// result in compilation errors.
type UnsafeFileServiceServer interface {
	mustEmbedUnimplementedFileServiceServer()
}

func RegisterFileServiceServer(s grpc.ServiceRegistrar, srv FileServiceServer) {
	// If the following call pancis, it indicates UnimplementedFileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileService_ServiceDesc, srv)
}

func _FileService_UploadUserAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadAvatarOrIconRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).UploadUserAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_UploadUserAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).UploadUserAvatar(ctx, req.(*UploadAvatarOrIconRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetUserAvatarUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvatarOrIconUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetUserAvatarUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetUserAvatarUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetUserAvatarUrl(ctx, req.(*GetAvatarOrIconUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_UploadActivityIcon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadAvatarOrIconRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).UploadActivityIcon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_UploadActivityIcon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).UploadActivityIcon(ctx, req.(*UploadAvatarOrIconRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetActivityIconUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvatarOrIconUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetActivityIconUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetActivityIconUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetActivityIconUrl(ctx, req.(*GetAvatarOrIconUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_UploadImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).UploadImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_UploadImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).UploadImage(ctx, req.(*UploadImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetImageUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImageUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetImageUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetImageUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetImageUrl(ctx, req.(*GetImageUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetFileUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetFileUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetFileUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetFileUrl(ctx, req.(*GetFileUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileService_ServiceDesc is the grpc.ServiceDesc for FileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "file_server.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadUserAvatar",
			Handler:    _FileService_UploadUserAvatar_Handler,
		},
		{
			MethodName: "GetUserAvatarUrl",
			Handler:    _FileService_GetUserAvatarUrl_Handler,
		},
		{
			MethodName: "UploadActivityIcon",
			Handler:    _FileService_UploadActivityIcon_Handler,
		},
		{
			MethodName: "GetActivityIconUrl",
			Handler:    _FileService_GetActivityIconUrl_Handler,
		},
		{
			MethodName: "UploadImage",
			Handler:    _FileService_UploadImage_Handler,
		},
		{
			MethodName: "GetImageUrl",
			Handler:    _FileService_GetImageUrl_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _FileService_UploadFile_Handler,
		},
		{
			MethodName: "GetFileUrl",
			Handler:    _FileService_GetFileUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "file_server.proto",
}
